# Muhammad Fazril Fahri
# AIH KELAS C - Universitas Ahmad Dahlan - 149294373101-1057

# Pemanfaatan TensorFlow dalam Manipulasi dan Pembentukan Tensor


In [1]:
# Mengimpor pustaka TensorFlow dan memberikan alias 'tf'

import tensorflow as tf


In [2]:
# Membuat konstanta dengan TensorFlow
con = tf.constant([[1, 2, 3, 4]], shape=[2, 2], dtype=tf.float32)

# Mencetak nilai dari konstanta 'con'
print(con)


tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float32)


In [3]:
#Menampilkan Atribut 
print("value of the constant ", con.numpy)
print("type of the constant ", con.dtype)
print("shape of the constant ", con.shape)
print("device of the constant ", con.device)

value of the constant  <bound method _EagerTensorBase.numpy of <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>>
type of the constant  <dtype: 'float32'>
shape of the constant  (2, 2)
device of the constant  /job:localhost/replica:0/task:0/device:GPU:0


In [4]:
# Membuat tensor yang berisi nol dengan bentuk yang sama seperti 'con'
zeros_like_c = tf.zeros_like(con)

# Mengambil nilai tensor 'zeros_like_c' dalam bentuk NumPy array dan mencetaknya
print(zeros_like_c.numpy())


[[0. 0.]
 [0. 0.]]


In [5]:
# Membuat tensor 3x3 yang diisi dengan angka 8
fill_d = tf.fill([3, 3], 8)

# Mengambil nilai tensor 'fill_d' dalam bentuk NumPy array dan mencetaknya
print(fill_d.numpy())


[[8 8 8]
 [8 8 8]
 [8 8 8]]


In [6]:
# Membuat tensor 5x5 dengan angka-angka acak terdistribusi normal
# dengan mean (rerata) 0, stddev (deviasi standar) 1.0, dan seed (benih) 2
random_e = tf.random.normal([5, 5], mean=0, stddev=1.0, seed=2)

# Mengambil nilai tensor 'random_e' dalam bentuk NumPy array dan mencetaknya
print(random_e.numpy())


[[-0.85811085 -0.19662298  0.13895045 -1.2212768  -0.40341285]
 [-1.1454041   0.63982403 -1.5766119  -1.0260106   0.6285083 ]
 [-0.82822376  0.34667715  1.3986595   1.0717978   1.2229327 ]
 [-0.07289016  0.416036    0.597757    0.6337952   0.41772613]
 [ 0.82624793 -1.1613202   0.844962   -0.89267987  1.3516175 ]]


In [7]:
# Membuat list 'list_f'
list_f = [1, 2, 3, 4, 5, 6]

# Menampilkan tipe data dari 'list_f'
print(type(list_f))


<class 'list'>


In [8]:
list_f

[1, 2, 3, 4, 5, 6]

In [9]:
# Mengonversi list 'list_f' menjadi tensor dengan tipe data 'tf.float32'
tensor_f = tf.convert_to_tensor(list_f, dtype=tf.float32)

# Menampilkan tensor 'tensor_f'
print(tensor_f)


tf.Tensor([1. 2. 3. 4. 5. 6.], shape=(6,), dtype=float32)


In [10]:
# Membuat variabel TensorFlow 'var_1' yang berisi tensor dengan angka 1
# dan bentuk [2, 3]
var_1 = tf.Variable(tf.ones([2, 3]))

# Menampilkan variabel 'var_1'
print(var_1)


<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>


In [11]:
# Mencetak isi dari variabel TensorFlow 'var_1' dengan menggunakan 'read_value()'
print("Isi dari variabel 'var_1':", var_1.read_value())


Isi dari variabel 'var_1': tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)


In [12]:
# Mengubah nilai dari variabel TensorFlow 'var_1' dengan menggunakan 'assign()'
var_value_1 = [[1, 2, 3], [4, 5, 6]]
var_1.assign(var_value_1)

# Mencetak nilai variabel 'var_1' setelah perubahan
print("Nilai 'var_1' setelah diubah:", var_1.read_value())


Nilai 'var_1' setelah diubah: tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]], shape=(2, 3), dtype=float32)


In [13]:
# Menambahkan nilai dari variabel TensorFlow 'var_1' dengan menggunakan 'assign_add()'
var_1.assign_add(tf.ones([2, 3]))

# Mencetak nilai variabel 'var_1' setelah penambahan
print("Nilai 'var_1' setelah penambahan:", var_1)


Nilai 'var_1' setelah penambahan: <tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[2., 3., 4.],
       [5., 6., 7.]], dtype=float32)>


In [14]:
# Membuat tensor 'tensor_h' dengan bentuk [4, 100, 100, 3]
# yang berisi angka-angka acak terdistribusi normal
tensor_h = tf.random.normal([4, 100, 100, 3])

# Menampilkan nilai dari tensor 'tensor_h'
print(tensor_h)


tf.Tensor(
[[[[ 9.32465792e-01 -2.12494805e-01 -7.85514593e-01]
   [ 6.48619056e-01  8.05307209e-01 -1.76586017e-01]
   [-1.22104096e+00  1.66484249e+00  1.32874668e+00]
   ...
   [ 6.54293224e-02  3.55380565e-01  2.36871362e-01]
   [-3.86538833e-01 -1.65288508e+00 -5.97667992e-01]
   [ 3.54238003e-02  4.86323714e-01 -8.20643678e-02]]

  [[ 1.74916244e+00 -2.26171359e-01  2.33568251e-01]
   [ 4.22944009e-01  1.05795681e+00  1.28164828e+00]
   [ 2.59378970e-01  1.02657509e+00 -1.45433009e+00]
   ...
   [ 5.03038526e-01  7.11538613e-01  2.77386576e-01]
   [ 6.42036676e-01  5.94639361e-01  8.62394691e-01]
   [ 3.91680837e-01 -8.55283797e-01  5.53858459e-01]]

  [[ 1.15282440e+00  3.57791901e-01  5.77022493e-01]
   [-9.79164779e-01  9.82981175e-04  2.18108356e-01]
   [ 1.81275487e+00 -1.51073694e+00  7.60088801e-01]
   ...
   [-1.02577001e-01  1.57632813e-01  9.42024350e-01]
   [ 2.04811141e-01 -6.50690317e-01  1.12943971e+00]
   [-9.17969227e-01 -1.46514440e+00 -4.09546047e-01]]

  ...

 

In [15]:
# Mengambil potongan dari tensor 'tensor_h' untuk indeks pertama (0) di semua dimensi lainnya
potongan_tensor_h = tensor_h[0, :, :, :]

# Menampilkan nilai dari potongan tensor 'potongan_tensor_h'
print(potongan_tensor_h)


tf.Tensor(
[[[ 9.3246579e-01 -2.1249481e-01 -7.8551459e-01]
  [ 6.4861906e-01  8.0530721e-01 -1.7658602e-01]
  [-1.2210410e+00  1.6648425e+00  1.3287467e+00]
  ...
  [ 6.5429322e-02  3.5538056e-01  2.3687136e-01]
  [-3.8653883e-01 -1.6528851e+00 -5.9766799e-01]
  [ 3.5423800e-02  4.8632371e-01 -8.2064368e-02]]

 [[ 1.7491624e+00 -2.2617136e-01  2.3356825e-01]
  [ 4.2294401e-01  1.0579568e+00  1.2816483e+00]
  [ 2.5937897e-01  1.0265751e+00 -1.4543301e+00]
  ...
  [ 5.0303853e-01  7.1153861e-01  2.7738658e-01]
  [ 6.4203668e-01  5.9463936e-01  8.6239469e-01]
  [ 3.9168084e-01 -8.5528380e-01  5.5385846e-01]]

 [[ 1.1528244e+00  3.5779190e-01  5.7702249e-01]
  [-9.7916478e-01  9.8298118e-04  2.1810836e-01]
  [ 1.8127549e+00 -1.5107369e+00  7.6008880e-01]
  ...
  [-1.0257700e-01  1.5763281e-01  9.4202435e-01]
  [ 2.0481114e-01 -6.5069032e-01  1.1294397e+00]
  [-9.1796923e-01 -1.4651444e+00 -4.0954605e-01]]

 ...

 [[-1.2923875e+00  1.0834516e+00 -1.1982353e+00]
  [-8.0872452e-01 -7.8930482

In [16]:
# Mengambil setiap elemen kedua (indeks 0 dan 2) pada dimensi pertama (indeks 0)
# dan semua elemen di dimensi lainnya
potongan_tensor_h = tensor_h[::2, ...]

# Menampilkan nilai dari potongan tensor 'potongan_tensor_h'
print(potongan_tensor_h)


tf.Tensor(
[[[[ 9.3246579e-01 -2.1249481e-01 -7.8551459e-01]
   [ 6.4861906e-01  8.0530721e-01 -1.7658602e-01]
   [-1.2210410e+00  1.6648425e+00  1.3287467e+00]
   ...
   [ 6.5429322e-02  3.5538056e-01  2.3687136e-01]
   [-3.8653883e-01 -1.6528851e+00 -5.9766799e-01]
   [ 3.5423800e-02  4.8632371e-01 -8.2064368e-02]]

  [[ 1.7491624e+00 -2.2617136e-01  2.3356825e-01]
   [ 4.2294401e-01  1.0579568e+00  1.2816483e+00]
   [ 2.5937897e-01  1.0265751e+00 -1.4543301e+00]
   ...
   [ 5.0303853e-01  7.1153861e-01  2.7738658e-01]
   [ 6.4203668e-01  5.9463936e-01  8.6239469e-01]
   [ 3.9168084e-01 -8.5528380e-01  5.5385846e-01]]

  [[ 1.1528244e+00  3.5779190e-01  5.7702249e-01]
   [-9.7916478e-01  9.8298118e-04  2.1810836e-01]
   [ 1.8127549e+00 -1.5107369e+00  7.6008880e-01]
   ...
   [-1.0257700e-01  1.5763281e-01  9.4202435e-01]
   [ 2.0481114e-01 -6.5069032e-01  1.1294397e+00]
   [-9.1796923e-01 -1.4651444e+00 -4.0954605e-01]]

  ...

  [[-1.2923875e+00  1.0834516e+00 -1.1982353e+00]
   [-

In [17]:
# Mengambil elemen-elemen tensor 'tensor_h' dalam urutan terbalik pada dimensi pertama (indeks 0)
potongan_tensor_h = tensor_h[::-1]

# Menampilkan nilai dari potongan tensor 'potongan_tensor_h'
print(potongan_tensor_h)


tf.Tensor(
[[[[ 2.93991584e-02  1.41924143e+00 -1.53057706e+00]
   [ 5.82536995e-01  1.55335951e+00 -4.98487771e-01]
   [-9.66047347e-01 -2.59018928e-01  7.68174082e-02]
   ...
   [ 1.33043599e+00 -1.54798424e+00  3.79962802e-01]
   [ 1.01681006e+00  1.34200037e+00  5.36589742e-01]
   [-6.68308958e-02  6.51962817e-01 -1.12307501e+00]]

  [[ 6.22912943e-01  1.37443304e+00  4.55243766e-01]
   [ 4.98125702e-01  3.79965931e-01  1.12908095e-01]
   [-6.27073705e-01 -2.96021819e-01  1.29836455e-01]
   ...
   [-6.70992732e-01  6.61307633e-01 -1.36196029e+00]
   [ 2.28135541e-01 -1.62712317e-02  1.65558076e+00]
   [-1.34736753e+00 -2.13523054e+00  6.27490938e-01]]

  [[-1.25793982e+00  1.37110770e+00 -2.17264816e-01]
   [-2.45068252e-01  1.89462379e-01  7.47194648e-01]
   [ 5.40714860e-01 -1.14997542e+00 -4.05803919e-01]
   ...
   [ 3.93796533e-01 -1.37681329e+00 -1.86617762e-01]
   [-1.55419216e-01  3.11661243e-01  3.40538710e-01]
   [ 5.13561785e-01 -3.08644772e-01 -6.12468123e-01]]

  ...

 

In [18]:
# Mengakses elemen dari tensor 'tensor_h' dengan indeks [0, 19, 39, 1]
elemen_tensor_h = tensor_h[0, 19, 39, 1]

# Menampilkan nilai dari elemen tensor yang diakses
print("Nilai elemen tensor:", elemen_tensor_h)


Nilai elemen tensor: tf.Tensor(0.9467081, shape=(), dtype=float32)


In [19]:
# Daftar indeks yang akan digunakan untuk pengumpulan
indices = [0, 1, 3]

# Menggunakan tf.gather untuk mengumpulkan elemen-elemen dari 'tensor_h'
# pada dimensi pertama (indeks 0) dengan indeks yang ada dalam 'indices'
# axis=0 mengindikasikan dimensi yang akan digunakan untuk pengumpulan
# batch_dims=1 mengindikasikan dimensi batch
hasil_gather = tf.gather(tensor_h, axis=0, indices=indices, batch_dims=1)

# Menampilkan hasil pengumpulan
print(hasil_gather)


tf.Tensor(
[[[[ 9.32465792e-01 -2.12494805e-01 -7.85514593e-01]
   [ 6.48619056e-01  8.05307209e-01 -1.76586017e-01]
   [-1.22104096e+00  1.66484249e+00  1.32874668e+00]
   ...
   [ 6.54293224e-02  3.55380565e-01  2.36871362e-01]
   [-3.86538833e-01 -1.65288508e+00 -5.97667992e-01]
   [ 3.54238003e-02  4.86323714e-01 -8.20643678e-02]]

  [[ 1.74916244e+00 -2.26171359e-01  2.33568251e-01]
   [ 4.22944009e-01  1.05795681e+00  1.28164828e+00]
   [ 2.59378970e-01  1.02657509e+00 -1.45433009e+00]
   ...
   [ 5.03038526e-01  7.11538613e-01  2.77386576e-01]
   [ 6.42036676e-01  5.94639361e-01  8.62394691e-01]
   [ 3.91680837e-01 -8.55283797e-01  5.53858459e-01]]

  [[ 1.15282440e+00  3.57791901e-01  5.77022493e-01]
   [-9.79164779e-01  9.82981175e-04  2.18108356e-01]
   [ 1.81275487e+00 -1.51073694e+00  7.60088801e-01]
   ...
   [-1.02577001e-01  1.57632813e-01  9.42024350e-01]
   [ 2.04811141e-01 -6.50690317e-01  1.12943971e+00]
   [-9.17969227e-01 -1.46514440e+00 -4.09546047e-01]]

  ...

 

In [20]:
# Membuat konstanta TensorFlow 'reshape_1' dengan bentuk awal [2, 3]
reshape_1 = tf.constant([[1, 2, 3], [4, 5, 6]])

# Menampilkan nilai konstanta 'reshape_1'
print("Nilai 'reshape_1':")
print(reshape_1)

# Mengubah bentuk konstanta 'reshape_1' menjadi [3, 2]
reshaped_tensor = tf.reshape(reshape_1, (3, 2))

# Menampilkan hasil pengubahan bentuk
print("Hasil pengubahan bentuk:")
print(reshaped_tensor)


Nilai 'reshape_1':
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
Hasil pengubahan bentuk:
tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)


In [21]:
# Membuat tensor 'expand_sample_1' dengan bentuk [100, 100, 3] dan angka-angka acak
expand_sample_1 = tf.random.normal([100, 100, 3], seed=1)

# Menampilkan bentuk (shape) dari tensor 'expand_sample_1'
print("Bentuk (shape) dari 'expand_sample_1':", expand_sample_1.shape)


Bentuk (shape) dari 'expand_sample_1': (100, 100, 3)


Kesimpulan :

1. Membuat Tensor: Dalam kasus ini, kita dapat membuat tensor dengan berbagai bentuk dan isi menggunakan TensorFlow. Contohnya adalah membuat tensor berisi angka acak terdistribusi normal, angka-angka tertentu, atau menggunakan fungsi tf.constant dan tf.fill.

2. Mengubah Bentuk Tensor: Kita dapat mengubah bentuk tensor menggunakan fungsi tf.reshape. Ini memungkinkan kita untuk mengorganisasi ulang elemen-elemen dalam tensor tanpa mengubah nilainya.

3. Mengakses Elemen Tensor: Elemen-elemen dalam tensor dapat diakses dengan mengindeksnya menggunakan tanda kurung siku. Kita dapat mengambil elemen tunggal atau potongan (slicing) dari tensor sesuai dengan kebutuhan.

4. Variabel TensorFlow: Variabel TensorFlow (dengan tf.Variable) digunakan untuk menyimpan parameter dan bobot dalam model machine learning. Variabel ini dapat diubah nilainya selama pelatihan model.

5. Menggunakan Fungsi tf.gather: tf.gather digunakan untuk mengumpulkan elemen-elemen dari tensor berdasarkan indeks yang ditentukan. Dimensi yang digunakan untuk pengumpulan dapat dikontrol menggunakan axis dan batch_dims.

6. Menggunakan Fungsi tf.squeeze: tf.squeeze digunakan untuk menghapus dimensi dengan ukuran 1 yang mungkin tidak diperlukan dalam tensor.

Selain itu, dalam case study ini kita juga telah memahami bagaimana mencetak nilai dari tensor serta beberapa atribut seperti bentuk (shape), tipe data (dtype), dan sebagainya. TensorFlow merupakan pustaka yang kuat untuk komputasi numerik dan deep learning, dan kode-kode tersebut mencerminkan penggunaannya dalam manipulasi data dan pembentukan tensor.